### ISSUE TITLE
ModuleNotFoundError: No module named 'boto3'

### ISSUE THREAD

**Issue by buhrmann** [conda-forge/smart_open-feedstock#5]
Hi, Is it possible that boto3 is missing from the dependencies? I get smart_open installed itself as a dependency of gensim. But when trying to import gensim or smart_open, boto3 is missing. Only boto (2) is installed as a dependency.

**Comment by menshikh-iv** [comment]
@buhrmann  this is strange because `boto3` already in `smart_open` dependencies: https://github.com/RaRe-Technologies/smart_open/blob/master/setup.py#L51.
Can you try to install `smart_open` from PyPI?

**Comment by souravsingh** [comment]
This is interesting, since ``boto3`` wasn't required for previous versions of conda tarballs and was installed directly.

**Comment by menshikh-iv** [comment]
@buhrmann can you confirm that problem resolved (I added missing dependencies in #6)?

**Comment by menshikh-iv** [comment]
ping @buhrmann

**Comment by buhrmann** [comment]
Sorry, I'll try to check tomorrow if this is resolved on my end. Thanks for looking into it!

**Comment by timkpaine** [comment]
https://github.com/conda-forge/smart_open-feedstock/pull/54
